/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ConstantsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "SQRT_RATIO_121_100"
      | "SQRT_RATIO_1_1"
      | "SQRT_RATIO_1_2"
      | "SQRT_RATIO_1_4"
      | "SQRT_RATIO_2_1"
      | "SQRT_RATIO_4_1"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "SQRT_RATIO_121_100",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SQRT_RATIO_1_1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SQRT_RATIO_1_2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SQRT_RATIO_1_4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SQRT_RATIO_2_1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SQRT_RATIO_4_1",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "SQRT_RATIO_121_100",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SQRT_RATIO_1_1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SQRT_RATIO_1_2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SQRT_RATIO_1_4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SQRT_RATIO_2_1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SQRT_RATIO_4_1",
    data: BytesLike
  ): Result;
}

export interface Constants extends BaseContract {
  connect(runner?: ContractRunner | null): Constants;
  waitForDeployment(): Promise<this>;

  interface: ConstantsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  SQRT_RATIO_121_100: TypedContractMethod<[], [bigint], "view">;

  SQRT_RATIO_1_1: TypedContractMethod<[], [bigint], "view">;

  SQRT_RATIO_1_2: TypedContractMethod<[], [bigint], "view">;

  SQRT_RATIO_1_4: TypedContractMethod<[], [bigint], "view">;

  SQRT_RATIO_2_1: TypedContractMethod<[], [bigint], "view">;

  SQRT_RATIO_4_1: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "SQRT_RATIO_121_100"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SQRT_RATIO_1_1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SQRT_RATIO_1_2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SQRT_RATIO_1_4"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SQRT_RATIO_2_1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SQRT_RATIO_4_1"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
