/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IDeploy, IDeployInterface } from "../../Redeploy.sol/IDeploy";

const _abi = [
  {
    type: "function",
    name: "deploy",
    inputs: [
      {
        name: "_data",
        type: "bytes",
        internalType: "bytes",
      },
      {
        name: "_salt",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "payable",
  },
] as const;

export class IDeploy__factory {
  static readonly abi = _abi;
  static createInterface(): IDeployInterface {
    return new Interface(_abi) as IDeployInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDeploy {
    return new Contract(address, _abi, runner) as unknown as IDeploy;
  }
}
