/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  InvalidReturnSizeProtocolFeeControllerTest,
  InvalidReturnSizeProtocolFeeControllerTestInterface,
} from "../../ProtocolFeeControllerTest.sol/InvalidReturnSizeProtocolFeeControllerTest";

const _abi = [
  {
    type: "function",
    name: "protocolFeeForPool",
    inputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          {
            name: "currency0",
            type: "address",
            internalType: "Currency",
          },
          {
            name: "currency1",
            type: "address",
            internalType: "Currency",
          },
          {
            name: "fee",
            type: "uint24",
            internalType: "uint24",
          },
          {
            name: "tickSpacing",
            type: "int24",
            internalType: "int24",
          },
          {
            name: "hooks",
            type: "address",
            internalType: "contract IHooks",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    stateMutability: "view",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610194806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063553bfc3714610030575b600080fd5b61004361003e3660046100be565b61005a565b60405161ffff909116815260200160405180910390f35b600080309050604051818152816020820152602081f35b6001600160a01b038116811461008657600080fd5b50565b803561009481610071565b919050565b803562ffffff8116811461009457600080fd5b8035600281900b811461009457600080fd5b600060a082840312156100d057600080fd5b60405160a0810181811067ffffffffffffffff8211171561010157634e487b7160e01b600052604160045260246000fd5b604052823561010f81610071565b8152602083013561011f81610071565b602082015261013060408401610099565b6040820152610141606084016100ac565b606082015261015260808401610089565b6080820152939250505056fea26469706673582212203a6a403d3305d7ab84840b652b0ddb0b0260c8a519a1fdf367edc8d5618dd2e464736f6c63430008130033";

type InvalidReturnSizeProtocolFeeControllerTestConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: InvalidReturnSizeProtocolFeeControllerTestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class InvalidReturnSizeProtocolFeeControllerTest__factory extends ContractFactory {
  constructor(
    ...args: InvalidReturnSizeProtocolFeeControllerTestConstructorParams
  ) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      InvalidReturnSizeProtocolFeeControllerTest & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): InvalidReturnSizeProtocolFeeControllerTest__factory {
    return super.connect(
      runner
    ) as InvalidReturnSizeProtocolFeeControllerTest__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): InvalidReturnSizeProtocolFeeControllerTestInterface {
    return new Interface(
      _abi
    ) as InvalidReturnSizeProtocolFeeControllerTestInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): InvalidReturnSizeProtocolFeeControllerTest {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as InvalidReturnSizeProtocolFeeControllerTest;
  }
}
