/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  RevertingProtocolFeeControllerTest,
  RevertingProtocolFeeControllerTestInterface,
} from "../../ProtocolFeeControllerTest.sol/RevertingProtocolFeeControllerTest";

const _abi = [
  {
    type: "function",
    name: "protocolFeeForPool",
    inputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          {
            name: "currency0",
            type: "address",
            internalType: "Currency",
          },
          {
            name: "currency1",
            type: "address",
            internalType: "Currency",
          },
          {
            name: "fee",
            type: "uint24",
            internalType: "uint24",
          },
          {
            name: "tickSpacing",
            type: "int24",
            internalType: "int24",
          },
          {
            name: "hooks",
            type: "address",
            internalType: "contract IHooks",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    stateMutability: "pure",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610178806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063553bfc3714610030575b600080fd5b61003e61002b3660046100a2565b60405161ffff909116815260200160405180910390f35b6001600160a01b038116811461006a57600080fd5b50565b803561007881610055565b919050565b803562ffffff8116811461007857600080fd5b8035600281900b811461007857600080fd5b600060a082840312156100b457600080fd5b60405160a0810181811067ffffffffffffffff821117156100e557634e487b7160e01b600052604160045260246000fd5b60405282356100f381610055565b8152602083013561010381610055565b60208201526101146040840161007d565b604082015261012560608401610090565b60608201526101366080840161006d565b6080820152939250505056fea2646970667358221220a73b8f8a22bdef36a897e078998328d6d7d6640490063b9ea10bd57788fa5af864736f6c63430008130033";

type RevertingProtocolFeeControllerTestConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RevertingProtocolFeeControllerTestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RevertingProtocolFeeControllerTest__factory extends ContractFactory {
  constructor(...args: RevertingProtocolFeeControllerTestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      RevertingProtocolFeeControllerTest & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): RevertingProtocolFeeControllerTest__factory {
    return super.connect(runner) as RevertingProtocolFeeControllerTest__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RevertingProtocolFeeControllerTestInterface {
    return new Interface(_abi) as RevertingProtocolFeeControllerTestInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RevertingProtocolFeeControllerTest {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as RevertingProtocolFeeControllerTest;
  }
}
