/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IProtocolFees, IProtocolFeesInterface } from "../IProtocolFees";

const _abi = [
  {
    type: "function",
    name: "MIN_PROTOCOL_FEE_DENOMINATOR",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "uint8",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolFeesAccrued",
    inputs: [
      {
        name: "",
        type: "address",
        internalType: "Currency",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "ProtocolFeeControllerUpdated",
    inputs: [
      {
        name: "protocolFeeController",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "FeeNotDynamic",
    inputs: [],
  },
  {
    type: "error",
    name: "ProtocolFeeCannotBeFetched",
    inputs: [],
  },
  {
    type: "error",
    name: "ProtocolFeeControllerCallFailedOrInvalidResult",
    inputs: [],
  },
] as const;

export class IProtocolFees__factory {
  static readonly abi = _abi;
  static createInterface(): IProtocolFeesInterface {
    return new Interface(_abi) as IProtocolFeesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProtocolFees {
    return new Contract(address, _abi, runner) as unknown as IProtocolFees;
  }
}
