/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUnlockCallback,
  IUnlockCallbackInterface,
} from "../IUnlockCallback";

const _abi = [
  {
    type: "function",
    name: "unlockCallback",
    inputs: [
      {
        name: "data",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    stateMutability: "nonpayable",
  },
] as const;

export class IUnlockCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IUnlockCallbackInterface {
    return new Interface(_abi) as IUnlockCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUnlockCallback {
    return new Contract(address, _abi, runner) as unknown as IUnlockCallback;
  }
}
