/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type PoolKeyStruct = {
  currency0: AddressLike;
  currency1: AddressLike;
  fee: BigNumberish;
  tickSpacing: BigNumberish;
  hooks: AddressLike;
};

export type PoolKeyStructOutput = [
  currency0: string,
  currency1: string,
  fee: bigint,
  tickSpacing: bigint,
  hooks: string
] & {
  currency0: string;
  currency1: string;
  fee: bigint;
  tickSpacing: bigint;
  hooks: string;
};

export declare namespace IPoolManager {
  export type ModifyLiquidityParamsStruct = {
    tickLower: BigNumberish;
    tickUpper: BigNumberish;
    liquidityDelta: BigNumberish;
  };

  export type ModifyLiquidityParamsStructOutput = [
    tickLower: bigint,
    tickUpper: bigint,
    liquidityDelta: bigint
  ] & { tickLower: bigint; tickUpper: bigint; liquidityDelta: bigint };
}

export interface PoolModifyLiquidityTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "manager"
      | "modifyLiquidity((address,address,uint24,int24,address),(int24,int24,int256),bytes,bool,bool)"
      | "modifyLiquidity((address,address,uint24,int24,address),(int24,int24,int256),bytes)"
      | "unlockCallback"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "modifyLiquidity((address,address,uint24,int24,address),(int24,int24,int256),bytes,bool,bool)",
    values: [
      PoolKeyStruct,
      IPoolManager.ModifyLiquidityParamsStruct,
      BytesLike,
      boolean,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "modifyLiquidity((address,address,uint24,int24,address),(int24,int24,int256),bytes)",
    values: [PoolKeyStruct, IPoolManager.ModifyLiquidityParamsStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockCallback",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "modifyLiquidity((address,address,uint24,int24,address),(int24,int24,int256),bytes,bool,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "modifyLiquidity((address,address,uint24,int24,address),(int24,int24,int256),bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockCallback",
    data: BytesLike
  ): Result;
}

export interface PoolModifyLiquidityTest extends BaseContract {
  connect(runner?: ContractRunner | null): PoolModifyLiquidityTest;
  waitForDeployment(): Promise<this>;

  interface: PoolModifyLiquidityTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  manager: TypedContractMethod<[], [string], "view">;

  "modifyLiquidity((address,address,uint24,int24,address),(int24,int24,int256),bytes,bool,bool)": TypedContractMethod<
    [
      key: PoolKeyStruct,
      params: IPoolManager.ModifyLiquidityParamsStruct,
      hookData: BytesLike,
      settleUsingTransfer: boolean,
      withdrawTokens: boolean
    ],
    [bigint],
    "payable"
  >;

  "modifyLiquidity((address,address,uint24,int24,address),(int24,int24,int256),bytes)": TypedContractMethod<
    [
      key: PoolKeyStruct,
      params: IPoolManager.ModifyLiquidityParamsStruct,
      hookData: BytesLike
    ],
    [bigint],
    "payable"
  >;

  unlockCallback: TypedContractMethod<
    [rawData: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "manager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "modifyLiquidity((address,address,uint24,int24,address),(int24,int24,int256),bytes,bool,bool)"
  ): TypedContractMethod<
    [
      key: PoolKeyStruct,
      params: IPoolManager.ModifyLiquidityParamsStruct,
      hookData: BytesLike,
      settleUsingTransfer: boolean,
      withdrawTokens: boolean
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "modifyLiquidity((address,address,uint24,int24,address),(int24,int24,int256),bytes)"
  ): TypedContractMethod<
    [
      key: PoolKeyStruct,
      params: IPoolManager.ModifyLiquidityParamsStruct,
      hookData: BytesLike
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "unlockCallback"
  ): TypedContractMethod<[rawData: BytesLike], [string], "nonpayable">;

  filters: {};
}
