/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IERC20Airdrop, IERC20AirdropInterface } from "../IERC20Airdrop";

const _abi = [
  {
    type: "function",
    name: "claim",
    inputs: [
      {
        name: "receiver",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "restAirdrop",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "totalAirdrop",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class IERC20Airdrop__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20AirdropInterface {
    return new Interface(_abi) as IERC20AirdropInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC20Airdrop {
    return new Contract(address, _abi, runner) as unknown as IERC20Airdrop;
  }
}
